import { Head, Link } from '@inertiajs/react';

const LAST_UPDATED = 'April 29, 2026';

const sections = [
    {
        title: '1. Who We Are',
        body: `Vyreo ("we", "our", "us") operates the Vyreo platform, a viral content marketing service connecting brands and creators. This Privacy Policy explains how we collect, use, and protect personal data when you use our website and services. If you have questions, contact us at privacy@vyreo.com.`,
    },
    {
        title: '2. Information We Collect',
        body: `We collect information you provide directly (name, email address, company details, payment information, bio, country), information generated by your use of the Platform (campaign data, entries, view counts, messages, earnings records), and technical information collected automatically (IP address, browser type, device identifiers, pages visited, referral URLs, cookies and similar tracking technologies). We also receive data from connected third-party social platforms (TikTok, Instagram, YouTube) such as follower counts, average views, and OAuth tokens — only with your explicit authorisation.`,
    },
    {
        title: '3. How We Use Your Information',
        body: `We use your data to: operate and improve the Platform; process payments and payouts via Stripe; verify social account metrics for campaign tracking; send transactional emails (via Resend) such as account confirmations, payout notifications, and campaign alerts; personalise your experience (discovery feeds, creator recommendations); enforce our Terms of Service; comply with legal obligations; and send you product updates and marketing communications (you may opt out at any time).`,
    },
    {
        title: '4. Legal Basis for Processing (GDPR)',
        body: `For users in the European Economic Area, our legal bases for processing are: Contract — processing necessary to fulfil our agreement with you (account management, payments, campaign delivery); Legitimate Interests — fraud prevention, Platform security, analytics, product improvements; Consent — marketing communications and optional cookies; Legal Obligation — compliance with applicable law.`,
    },
    {
        title: '5. Social Platform Data',
        body: `When you connect a social account (TikTok, Instagram, YouTube), we store an encrypted OAuth token and periodically sync follower counts, average views, and engagement rates. This data is used solely to verify performance metrics for campaign payouts. We do not post on your behalf, access direct messages, or store data beyond what is necessary for campaign tracking. You may disconnect a social account at any time from Settings → Social Accounts, which revokes our access.`,
    },
    {
        title: '6. Payment Data',
        body: `Payment processing is handled entirely by Stripe. We do not store full card numbers or bank account details on our servers. We retain Stripe customer IDs, subscription status, and payout history for billing records and dispute resolution. Stripe's own Privacy Policy governs how Stripe processes your financial data.`,
    },
    {
        title: '7. Sharing Your Information',
        body: `We do not sell your personal data. We share data only with: service providers acting on our behalf (Stripe for payments, Resend for email, Cloudflare R2 for file storage, Redis/PostgreSQL for data storage); the other party in a campaign transaction (e.g., brands see creator handles and verified stats; creators see brand names and campaign briefs); and law enforcement or regulators when required by law or to protect rights and safety. All service providers are bound by data processing agreements.`,
    },
    {
        title: '8. Data Retention',
        body: `We retain your account data for as long as your account is active. If you delete your account, we remove personal data within 30 days, except where we are required to retain it for legal or tax purposes (typically 7 years for financial records). Anonymised or aggregated analytics data may be retained indefinitely.`,
    },
    {
        title: '9. Cookies & Tracking',
        body: `We use strictly necessary cookies for session management and authentication. We use analytics cookies (with your consent) to understand how users interact with the Platform and improve features. You can manage cookie preferences through your browser settings. Disabling strictly necessary cookies will prevent you from logging in.`,
    },
    {
        title: '10. Security',
        body: `We implement industry-standard safeguards including TLS encryption in transit, AES-256 encryption at rest for sensitive fields (OAuth tokens), bcrypt password hashing, and regular security reviews. No system is 100% secure. If you discover a security vulnerability, please disclose it responsibly to security@vyreo.com.`,
    },
    {
        title: '11. Your Rights',
        body: `Depending on your jurisdiction, you may have rights to: access the personal data we hold about you; correct inaccurate data; request deletion of your data ("right to be forgotten"); object to or restrict certain processing; data portability (receive your data in a machine-readable format); and withdraw consent at any time where processing is based on consent. To exercise any of these rights, email privacy@vyreo.com. We will respond within 30 days.`,
    },
    {
        title: '12. International Transfers',
        body: `Your data may be stored and processed in countries outside your own, including the United States and the European Union, where our service providers operate. When transferring data out of the EEA, we rely on Standard Contractual Clauses or adequacy decisions as the legal mechanism for transfer.`,
    },
    {
        title: '13. Children',
        body: `The Platform is not directed at children under 18. We do not knowingly collect personal data from anyone under 18. If you believe a minor has created an account, contact us at privacy@vyreo.com and we will delete the data promptly.`,
    },
    {
        title: '14. Changes to This Policy',
        body: `We may update this Privacy Policy from time to time. We will notify you of material changes by email or in-app notice at least 14 days before they take effect. The "Last updated" date at the top of this page reflects the most recent revision.`,
    },
    {
        title: '15. Contact Us',
        body: `For any privacy-related questions or to exercise your rights, contact our Data Protection team at privacy@vyreo.com or write to: Vyreo Privacy, [Company Address]. If you are in the EEA and are not satisfied with our response, you have the right to lodge a complaint with your local data protection authority.`,
    },
];

export default function Privacy() {
    return (
        <>
            <Head title="Privacy Policy — Vyreo" />

            <div className="min-h-screen bg-white text-gray-900 antialiased dark:bg-gray-950 dark:text-gray-50">
                {/* Navbar */}
                <header className="sticky inset-x-0 top-0 z-50 border-b border-gray-200/60 bg-white/80 backdrop-blur-md dark:border-gray-800/60 dark:bg-gray-950/80">
                    <div className="mx-auto flex h-16 max-w-4xl items-center justify-between px-4 sm:px-6">
                        <Link href="/" className="flex items-center gap-2">
                            <img
                                src="/logo/vyreio_logo_light.svg"
                                alt="Vyreo"
                                className="h-8 w-auto dark:hidden"
                            />
                            <img
                                src="/logo/vyreio_logo_dark.svg"
                                alt="Vyreo"
                                className="hidden h-8 w-auto dark:block"
                            />
                        </Link>
                        <Link
                            href="/terms"
                            className="text-sm text-gray-500 hover:text-gray-900 dark:hover:text-gray-200"
                        >
                            Terms of Service
                        </Link>
                    </div>
                </header>

                {/* Content */}
                <main className="mx-auto max-w-4xl px-4 py-16 sm:px-6">
                    <div className="mb-12">
                        <h1 className="mb-3 text-4xl font-bold tracking-tight">
                            Privacy Policy
                        </h1>
                        <p className="text-sm text-gray-500 dark:text-gray-400">
                            Last updated: {LAST_UPDATED}
                        </p>
                        <p className="mt-4 leading-relaxed text-gray-600 dark:text-gray-300">
                            Your privacy matters to us. This policy explains
                            exactly what data Vyreo collects, why we
                            collect it, and how you can control it.
                        </p>
                    </div>

                    <div className="space-y-10">
                        {sections.map((section) => (
                            <section key={section.title}>
                                <h2 className="mb-3 text-xl font-semibold">
                                    {section.title}
                                </h2>
                                <p className="leading-relaxed text-gray-600 dark:text-gray-300">
                                    {section.body}
                                </p>
                            </section>
                        ))}
                    </div>
                </main>

                {/* Footer */}
                <footer className="mt-16 border-t border-gray-200 py-10 dark:border-gray-800">
                    <div className="mx-auto flex max-w-4xl flex-col items-center justify-between gap-4 px-4 sm:flex-row sm:px-6">
                        <p className="text-xs text-gray-500">
                            © {new Date().getFullYear()} Vyreo. All
                            rights reserved.
                        </p>
                        <div className="flex gap-6 text-xs text-gray-500">
                            <Link
                                href="/terms"
                                className="hover:text-gray-900 dark:hover:text-gray-200"
                            >
                                Terms of Service
                            </Link>
                            <Link
                                href="/privacy"
                                className="hover:text-gray-900 dark:hover:text-gray-200"
                            >
                                Privacy Policy
                            </Link>
                        </div>
                    </div>
                </footer>
            </div>
        </>
    );
}
